services:
  eureka-server:
    image: ofentselekgetho/safety_encrypt:eureka-server-v1
    container_name: eureka-server
    ports:
      - 8761:8761

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true


  crypto-service:
    image: ofentselekgetho/safety_encrypt:crypto_service-v11
    container_name: crypto-service
    depends_on:
      - eureka-server
      - api-gateway
    ports:
      - 8100:8100


  api-gateway:
    image: ofentselekgetho/safety_encrypt:api-gateway-v5
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - 8080:8080
