services:
  eureka-server:
    image: ofentselekgetho/safety_encrypt:eureka-server-v1
    container_name: eureka-server
    ports:
      - 8761:8761

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # OTLP gRPC

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command: [ "--config=/etc/otel/config.yaml" ]
    depends_on:
      - jaeger


  crypto-service:
    image: ofentselekgetho/safety_encrypt:crypto_service-v8
    container_name: crypto-service
    depends_on:
      - eureka-server
      - api-gateway
      - otel-collector
    ports:
      - 8100:8100


  api-gateway:
    image: ofentselekgetho/safety_encrypt:api-gateway-v5
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - 8080:8080
