spring:
  application:
    name: crypto-service
  profiles:
    active: dev

default:
  encodingalgo: Base64
  hashingalgo: Argon2
  passwordlength: 8


server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ENDPOINT:http://eureka-server:8761/eureka}


management:
  tracing:
    sampling:
      probability: ${OTEL_TRACING_SAMPLING_PROBABILITY:1.0}

  otlp:
    tracing:
      endpoint: ${OTEL_TRACING_ENDPOINT:http://otel-collector:4319/v1/traces}

